FROM golang:1.9 as builder
WORKDIR /go/src/github.com/halfrost/threes-ai
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o threes-ai .

FROM alpine:latest
LABEL maintainer="ydz@627@gmail.com"
RUN apk --no-cache add ca-certificates tzdata \
			&& cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
			&& echo "Asia/Shanghai" >  /etc/timezone \
			&& apk del tzdata
WORKDIR /root/threes-ai
COPY --from=builder /go/src/github.com/halfrost/threes-ai/threes-ai .
EXPOSE 9000
CMD ["./threes-ai"]
